### ISSUE TITLE
[IText] Selection box breaks when changing IText text style

### ISSUE THREAD

**Issue by marcospassos** [kangax/fabric.js#2049]
I was testing the PR #1778 and I noticed that changing the style of an active object breaks the selection box. It looks like a bug once I'm calling the `setCoords()` before.

An workaround is reset the active object which redraws correctly the selection box.

Fiddle:
http://jsfiddle.net/51u08n39/67/

**Comment by asturur** [comment]
Does it happens even on current code base?
Please do not open issues on unmergedPR or old codebase.

**Comment by marcospassos** [comment]
Sorry, no, it's not.

**Comment by marcospassos** [comment]
@asturur I can reproduce it on current master:
http://jsfiddle.net/51u08n39/77/

**Comment by asturur** [comment]
So setSelectionStyles should clear cache.

**Comment by marcospassos** [comment]
@asturur Please, take a look at this updated test:
http://jsfiddle.net/51u08n39/78/

**Comment by marcospassos** [comment]
Added a timeout for better explaining:
http://jsfiddle.net/51u08n39/79/

**Comment by asturur** [comment]
Height shift bug is no more present.
Do no refer to current master but build it from source.
Some commits happened since last build.
On of those solved this.

**Comment by Noumankhan80** [comment]
@marcospassos I am having the same issue. I did not PR #1778 . When change the font size selection box and text not at same place. I see your fiddle this is bug, Have any one sort it yet or any solution.?

**Comment by Noumankhan80** [comment]
@marcospassos  I have found a solution and apply it to my code and its working, You neet to setCoords of active object on font size change like: 

var el = canvas.getActiveObject();
	el.setCoords();
canvas.renderAll()

Hope this is work for you.

**Comment by asturur** [comment]
Guys, as i wrote before, setSelectionStyles should clear cache of text object.
That's all.
i m gonna make a pr to close the bug.

**Comment by asturur** [comment]
Fixed with latest commit. https://github.com/kangax/fabric.js/commit/84bd8bbda067425bf5ee13b6c755f332e8527939

**Comment by marcospassos** [comment]
Thanks, @asturur!

**Comment by daochung** [comment]
This bug still there in Fabricjs 1.5.0
Anybody have solution, pls let me know...

**Comment by asturur** [comment]
you have to download and build latest source OR wait for 1.5.1

fix is in the link 2 posts above your.

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/commit/cfd7521482508b934df9c188ef7787d54b460b69


sorry this is solution.
build new version you will get more fixes.

**Comment by daochung** [comment]
I found 2 issues. http://screencast.com/t/zI1GUWe13meK
1. It doesn't update when change font-size
2. when select copy text and change color, it autos change other text too.

**Comment by asturur** [comment]
Selection box works when you change font size or familty, in style or to object.
This i'm sure.

For the other issue open a new issue with a jsfiddle example to speed up fixing.

**Comment by daochung** [comment]
I added some code there: http://jsfiddle.net/kienlua/51u08n39/99/
1. when you change font-size you can see the box doesn't clear cache.
2. when select copy text and change color, it autos change other text too.

**Comment by daochung** [comment]
btw, do you have solution for text like this?
http://csswarp.eleqtriq.com/
Thanks

**Comment by sapics** [comment]
Current master version has already fix about `1`.
http://jsfiddle.net/sapics/51u08n39/104/

**Comment by daochung** [comment]
Thanks sapics.
This is issue about 2: http://screencast.com/t/31tImyE0Q

**Comment by asturur** [comment]
we cannot generate curve text yet. There is a PR we have to adapt after 1.5.1 release.

**Comment by daochung** [comment]
I saw new issue in I-Text.
color issue: http://screencast.com/t/QohjiGjNTJym

**Comment by GiseleLima** [comment]
The problem reported by @daochung has been resolved?
