### ISSUE TITLE
IText/Textbox - The first character is ignored when you type after selecting all text

### ISSUE THREAD

**Issue by jafferhaider** [kangax/fabric.js#2451]
Steps for recreating:
1. Type some text into IText or Textbox
2. Use keyboard shortcut to select all (Cmd+A)
3. Type some more text. The first character that you type will not appear in the text. Text will start updating when the 2nd character is entered.

This is a recent issue, haven't come across it in the older builds. Any ideas @asturur?

**Comment by kangax** [comment]
We need to start adding functional tests where characters are being typed, removed, selected, etc.

**Comment by marcovdijk** [comment]
Couldn't this be related to #2448?

**Comment by FabianLauer** [comment]
I can confirm this:

![capture17092015114005](https://cloud.githubusercontent.com/assets/2205595/9997006/3db9c0bc-608a-11e5-91a7-bac51c6c7396.gif)

**Comment by FabianLauer** [comment]
I don't have the time to write tests at the moment (thus no pull request), but I did find a few minutes to try something out. I *think* that replacing the `onInput` method in src/mixins/itext_key_behavior.mixin.js with this might solve the problem:


    onInput: function(e) {
    if (!this.isEditing || this._cancelOnInput) {
		this._cancelOnInput = false;
		return;
	}
	var offset = this.selectionStart || 0,
		textLength = this.text.length,
		newTextLength = this.hiddenTextarea.value.length,
		diff = newTextLength - textLength,
		charsToInsert;
	
	if (this.selectionEnd !== 0 && this.selectionEnd !== this.selectionStart && this.selectionEnd === this.text.length) {
		charsToInsert = this.hiddenTextarea.value;
		this._removeCharsFromTo(this.selectionStart, this.selectionEnd);
	} else {
		charsToInsert = this.hiddenTextarea.value.slice(offset, offset + diff);
	}
	
	this.insertChars(charsToInsert);
	e.stopPropagation();
     }


Hope this is at least somewhat helpful.

**Comment by asturur** [comment]
found the error and solved. PR is coming.
It was a general error on deciding wich was the new text to add.

**Comment by FabianLauer** [comment]
Great news, just made my monday morning. Thanks :smile:

**Comment by ykka** [comment]
This I think still happens on 1.6.0, or it has been fixed already?
thanks!

**Comment by asturur** [comment]
It has been fixed. There are some little problems with internet explorer 11 or edge.

**Comment by deepdoon** [comment]
It is still not working for IE 11. Any solution that can do the fix?
Thanks

**Comment by deepdoon** [comment]
any update?? please

**Comment by schacki** [comment]
This is still not working with 1.6 and Chrome. Any update?

**Comment by asturur** [comment]
can you replicate the problem in a fiddle? to me it works.
Please tell us also operating system and keyboard type (latin, american, italian...)

**Comment by deepdoon** [comment]
@asturur  It is not working in IE 11. I checked the same fiddle [http://jsfiddle.net/kg9weds5/8/](http://jsfiddle.net/kg9weds5/8/) . Double click to edit. Select all text type something you will see the bug.

**Comment by asturur** [comment]
i try today and investigate.

**Comment by deepdoon** [comment]
Thanks.

**Comment by schacki** [comment]
I was working with a RC version. After upgrading to 1.6.2 this has been fixed on Chrome

**Comment by deepdoon** [comment]
yea but problem still persists in IE.

**Comment by asturur** [comment]
ie11 or ie edge?

**Comment by deepdoon** [comment]
IE 11. haven't checked it on edge.

**Comment by butch2k** [comment]
Same issue with chrome btw.

**Comment by deepdoon** [comment]
for me it worked fine with chrome.  I am using chrome Version 51.0.2704.103

**Comment by awehring** [comment]
I can confirm the bug for  IE 11 (exactly: 11.0.9600.18349) for deepdoons jsfiddle..

**Comment by asturur** [comment]
guys fiddle runs on 1.6.0-rc1

**Comment by deepdoon** [comment]
Hi @asturur it is still not working for IE11 using 1.6.0-rc1 and 1.6.3. Steps that i followed for  [ http://jsfiddle.net/kg9weds5/8/](http://jsfiddle.net/kg9weds5/8/) are:

1. Open the link in IE11.
2. Double click the text object to get it into edit mode.
3. Select all text either by mouse or by presing ctrl + A
4. Once text is selected type any letter lets say 'd'. 
5. 'd' will not be displayed type another letter and that will get displayed. 

So it is still skipping first letter in IE 11. 

Thanks

**Comment by asturur** [comment]
ok i could replicate finally.

**Comment by deepdoon** [comment]
@asturur I agree that it leaves first character from old text but along with this it does not show the character you have pressed. 
Lets say we have selected complete text and now pressing three character 'd', 'e' and 'f'. So the result would be one character from old text and 'e' and 'f'. Character 'd' will be ignored.

I hope this helps.

**Comment by lambdazen** [comment]
Ran into this problem with IE11. Here's a JSFiddle test case: http://jsfiddle.net/ewu2u5dr/1/
