### ISSUE TITLE
[Group] Incorrect objects transform within group

### ISSUE THREAD

**Issue by grimor** [kangax/fabric.js#2515]
I've found out issue when I transform objects within group. I'm posting gif visualizing the issue. Tried to solve it myself, but no luck so far. 

![Transform issue](http://i.imgur.com/rOycwPX.gif)

It draws object incorrectly, after discarding group it have proper transforms. Also like you see, objects bounding box borders are drawn correctly.

**Comment by kangax** [comment]
Hm, I think this should be fixed in latest build (now that we have skew support) /cc @asturur

**Comment by asturur** [comment]
no is not fixed, we need to solve all group related object transformation.

**Comment by asturur** [comment]
please check #2549 to see current status. flipping not working good yet. Control boxes will be fixed later.
