### ISSUE TITLE
toDataUrl exports are automatically scaled up and cropped on 1.6RC

### ISSUE THREAD

**Issue by shlomokraus** [kangax/fabric.js#2744]
When I use toDataUrl on a canvas, it exports the image scaled up and cropped. 
It has the same behaviour even if I set multiplier, size or top/left position. 

Reverting back to 1.5 fixed the issue.

**Comment by asturur** [comment]
can you post a fiddle that demonstrate the problem? thanks.

**Comment by ahmadissa** [comment]
facing same issue with 1.6RC, the strange thing is that it happens only when using my windows 10 laptop, it does not happen when using my ubuntu, both using the latest chrome. im not sure if its related to graphics capability of the laptop

**Comment by ahmadissa** [comment]
Solved in the below way: 

var fabricJScanvas  = new fabric.Canvas('"myCanvasID");

Used:
var canvas = document.getElementById("myCanvasID");
canvas.toDataURL('image/jpeg', 0.92);

instead of:
fabricJScanvas.toDataURL('image/jpeg');

I dont know how this make scene, but its working. 

@shlomokraus this might solve your issue too

**Comment by asturur** [comment]
you did not solve, you avoided calling the dataUrl exporter.
A fiddle is needed to test it.
Anyone willing to prepare it?

**Comment by AdamMerrifield** [comment]
@asturur [Here is an interesting example](https://jsfiddle.net/NfZVb/260/) I just added to the `toDataURL` demo jsFiddle link and updated the fabric.js external resource to `1.6.0-rc.1`

You can see the canvas and how it gets rendered and then in the console you can see a couple data uri's, none of which look correct (except the last one which avoids the dataUrl exporter like above.)

**Comment by asturur** [comment]
They all look correct to me except for the cropped one of which  cannot guarantee correctness using only eyes.
All others are fine.

I'm using windows 8.1 and chrome.

**Comment by AdamMerrifield** [comment]
[Here is an album of each of these images that i'm getting](https://imgur.com/a/N9rPi)

Mac Version 10.11.3 (15D21)

Google Chrome Version 47.0.2526.111 (64-bit)

same thing happens on: 

Safari Version 9.0.3 (11601.4.4)

**Comment by asturur** [comment]
You are getting the "retina enanched" version of the canvas. that is correct yes.

When we prepare the canvas for toDataUrl we should reset the retina scaling maybe. This is a bug i will have tons of problem to iron out.

**Comment by AdamMerrifield** [comment]
Looks like you're correct. Setting `enableRetinaScaling: false` on the canvas fixes this problem for me.

**Comment by asturur** [comment]
@kangax what do you think, a mac user, should expect when dataurling his fabricjs canvas?

To get the normal version everyone gets or to get the retina scaled version?

because this decision influence the fix.

**Comment by kangax** [comment]
I think retina version.

**Comment by asturur** [comment]
Someone care to try #2806? it fixes retina export of canvas to dataUrl.

**Comment by AdamMerrifield** [comment]
@asturur Everything looks correct to me now. I've only checked a mac though, can someone check a PC? See if all the images corrospond to the ones I'm seeing [Here is an fiddle with the new js from your pull request](https://jsfiddle.net/NfZVb/296/) [Here is an album of each image](https://imgur.com/a/Vmi1M)

**Comment by asturur** [comment]
i'm on pc and it looks correct for me.
