### ISSUE TITLE
1.6.0-rc.1 fails to install canvas@1.1.6

### ISSUE THREAD

**Issue by mDomingues** [kangax/fabric.js#2789]
Hi,

When I try to install the latest version, it is always crashing installing _canvas@1.1.6_.
Basically its the output bellow:

```
npm WARN engine fabric@1.6.0-rc.1: wanted: {"node":">=0.4.0 && <1.0.0"} (current: {**"node":"0.12.10","npm":"2.14.9"**})
-
> canvas@1.1.6 install /Users/xx/git/app/node_modules/fabric/node_modules/canvas
> node-gyp rebuild

which: no ldconfig in (/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/xx/git/app/node_modules/fabric/node_modules/canvas/node_modules/.bin:/Users/xx/git/app/node_modules/fabric/node_modules/.bin:/Users/xx/git/app/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin)
gyp: Call to './util/has_lib.sh jpeg' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1075:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xx/git/app/node_modules/fabric/node_modules/canvas
gyp ERR! node -v v0.12.10
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

All node-canvas are correctly satisfied and everything installed. Can't get this to work.
Summary of what I've:

```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: a47301174cb01f868bba5cf599e05c9aabb937f0
Last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit ivybridge
OS X: 10.11.1-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
Clang: 7.0 build 700
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.0/bin/ruby
Java: 1.8.0_72, 1.6.0_65-b14-468
```
 

Any ideas ?

**Comment by StephanBijzitter** [comment]
Try to install `node-gyp` globally, it shouldn't be needed, but sometimes helps

**Comment by mDomingues** [comment]
I did it already..
Any clues for what's happening ?

**Comment by StephanBijzitter** [comment]
Did you also install the following dependencies too?
`brew install pkg-config cairo libpng jpeg giflib` using [HomeBrew for OS X](http://brew.sh)

**Comment by mDomingues** [comment]
Done it too. 

![image](https://cloud.githubusercontent.com/assets/11029958/13046129/0349566e-d3cf-11e5-9ceb-cfbb76b47aa4.png)

**Comment by StephanBijzitter** [comment]
Then, sadly, I have no further ideas. This worked for me

**Comment by asturur** [comment]
Did you try with canvas 1.2.x? The current code database has 1.2.X as a dependency

**Comment by asturur** [comment]
Did you try with canvas 1.2.x? The current code database has 1.2.X as a dependency

**Comment by StephanBijzitter** [comment]
Yes, I checked out master and ran npm install. I first ran into the same issue as you, but the steps above fixed it for me.

**Comment by LinusU** [comment]
@mDomingues Could you try with a later version of canvas? I fixed that error in Automattic/node-canvas#701

**Comment by mDomingues** [comment]
With a later version of canvas it works. 
The problem is with that specific version of `fabric` that requires `canvas@1.1.6`.

Apparently I solved it. A `node-gyp rebuild`, `brew unlink node && brew link node` and a fresh install of all dependencies solved it.

Distressful things... Many thanks guys! 
Hope this helps someone in the future.

**Comment by stefanhuber** [comment]
This is still a problem! There is no way installing fabric via npm!

**Comment by LinusU** [comment]
Please open an issue with fabric, since they depend on an old version of canvas we can't fix anything from our side. Thank you

**Comment by asturur** [comment]
there are some internal changes to do to bump canvas to 1.3.x i noticed.
Did you try to use canvas 1.2.x?

**Comment by LinusU** [comment]
Mind elaborating? 1.3.x should be backwards compatible, and if it isn't we have failed somewhere. Maybe we could help out from our side?

**Comment by asturur** [comment]
I'm sorry i confused myself with jsdom upgrade necessary for node 4, that wraps nodecanvas in a different way. so not consider my post. i'm gonna delete it.

We are on 1.2.x and i think it is safe to bump to 1.3.x.
I will test latest nodecanvas and if i get no problems i will update the packages.json here

Upgrading npm package is another story, i cannot do it.

**Comment by asturur** [comment]
update to canvas 1.3.x now.
