### ISSUE TITLE
dataToURL multiplier bug? (Creating superimposed duplicates)

### ISSUE THREAD

**Issue by edvincandon** [kangax/fabric.js#2873]
## Version 1.5.0

I think I came across a bug when applying the` dataToURL({options})` method on a Path object, on the codepen below I have created 3 objects : 

[http://codepen.io/edvincandon/pen/YqYZOj](http://codepen.io/edvincandon/pen/YqYZOj)

- the first one is a simple triangle Path added to the canvas
- the middle one is that same path passed through dataToURL with: `{format: 'png', multiplier: 1.5}`
- the last one is the same path, this time passed through dataToURL with `{format: 'jpeg', multiplier: 1.5}`

Apart from not maintaining transparency, the JPEG output is correct.
**On the other hand**, it seems the PNG output is **superimposing** the previous path below/under. I think this has to do with the multiplier (setting it to **<=1** fixes the issue). Can't find the reason it's doing that, I know the dataToURL on an object is done on a temporary` StaticCanvas`, but still can't find the issue.. 

In my case, I really need to use the multiplier while keeping PNG transparency, so if anyone has a fix?

**Comment by asturur** [comment]
please try with latest version also.

**Comment by edvincandon** [comment]
Yes sir, will get back to you ASAP, I thought I was up to date..

**Comment by asturur** [comment]
but i remember that this bug was happening for some double redraw without clearing. is solved for sure in curret github codebase.

**Comment by edvincandon** [comment]
Yep, latest build fixes this issue, sorry for the trouble.

**Comment by edvincandon** [comment]
Actually, issue is still here with the latest build
http://codepen.io/edvincandon/pen/wGpddM

**Comment by asturur** [comment]
please i have some problem logging in to codepen with github so i cannot save my codepen fork. link this version that is the latest built one ```http://www.deltalink.it/andreab/fabric/fabric.js```  and you will see no problem then.

**Comment by edvincandon** [comment]
Yep, your version works perfect. Thank you very much for the quick response!
What I don't get it is that I had just done a clean build.. Anyways, issue closed!
