### ISSUE TITLE
Latest beta (6) causes issues with free drawing

### ISSUE THREAD

**Issue by rockmacaca** [kangax/fabric.js#4248]
Unfortunately (for me!) you probably won't see this for a couple weeks, but here's what I've found with the issue so far:

After mouseup drawing a path, the resulting path is rendered with some incorrect offset. The beta 6 dist on NPM behaves a bit differently than master and the site demo.

#4196 specifically broke it initially. On this commit, drawn paths look like its points use coordinates that are relative to a top left origin but the path is rendered using a centered origin.

Some later change after the published beta 6 makes it so that it is rendered shifted toward the bottom right a fixed distance. It also behaves like this on the beta 6 npm build by stripping the `originX` and `originY` properties as soon as the path is created.

The only other thing I have to add is that the offsets go away when I'm serializing + deserializing the paths on my DB.

## Version
2.0.0-beta.6

## Test Case
http://fabricjs.com/freedrawing

**Comment by asturur** [comment]
i think this is fixed. i probably did not update the website.
Maybe is just on my hard disk, let me check.

**Comment by felipepucinelli** [comment]
Hello,

I'm using the npm package and still having this issue, how can I fix it, please?

**Comment by asturur** [comment]
what about beta 7?

**Comment by felipepucinelli** [comment]
@asturur Hi!
So, I removed the version I was usign (fabric@2.0.0-beta.6) and try to add the new one by npm using: `yarn add fabric@2.0.0-beta.7` but i'm still having this issue :(

**Comment by asturur** [comment]
fabricjs.com has latest beta7. can you replicate the issue there? or on jsfiddle?

**Comment by felipepucinelli** [comment]
The latest beta7 is available in any CDN? jsfiddle didn't allow me to you the fabricjs.com source

**Comment by felipepucinelli** [comment]
You are absolutely right, the beta.7 is working, maybe this is a cache related issue in my project.

Anyway, thank you 👍 

Fiddle Test: https://fiddle.jshell.net/qj4v4ft5/
