### ISSUE TITLE
Freedraw mode object displacement in 2.0.0

### ISSUE THREAD

**Issue by karltaidev** [kangax/fabric.js#4310]
The freedraw object displace after update to 2.0.0 beta 6
The fiddle is forked from issue #4299 and I change the fabricjs file to 2.0.0 to demonstrate the difference. You could ignore the controls and just draw on the canvas.

## Version
2.0.0 beta 6

## Test Case
https://jsfiddle.net/karldev/g1kn96mL/

**Comment by asturur** [comment]
But this is fixed if you update to latest code. free draw is no more displaced.

**Comment by karltaidev** [comment]
Did you try the fiddle? I am using the latest 2.0.0 beta 6 version. Even If I download the file from dist folder, the issue still there. http://fabricjs.com/freedrawing has no displacement issue though, but it has another issue when adding object for the js file.

**Comment by karltaidev** [comment]
I have replace the function "fabric.PencilBrush = fabric.util.createClass(fabric.BaseBrush, /** @lends fabric.PencilBrush.prototype */ {...});" section with the JS inside the demo page. This fixes the issue. It would be great if the issue is fixed in the latest dist and CDN.

**Comment by asturur** [comment]
The dist folder is not updated with the latest code every day.
Is at least 10 commits older now.

Fabricjs.com is updated with latest one each time i work on it, but updating the DIST folder here creates unnecessary large commits in the history file
