### ISSUE TITLE
iText doesn't recalculate its "outer" dimensions when its inner content is changed by typing or by font size enlargement

### ISSUE THREAD

**Issue by finom** [kangax/fabric.js#4383]
## Version
1.7.19

## Test Case
http://fabricjs.com/test/misc/itext.html

## Steps to reproduce
- Focus any iText example (in my case it's "Styled & with empty line")
![image](https://user-images.githubusercontent.com/1082083/31575803-41acd2da-b0f7-11e7-867d-abf1640cbed8.png)
- Change its text so the object changes it width
![](https://i.imgur.com/bhy9ia3.png)
- Blur it and click on the object area outside of previous text value (in my case on "bar" at "foobar").

## Expected Behavior

It should make the iText object active.

## Actual Behavior

The click does nothing. To activate the object you need to click at older value area (in my case "foo") and the object backs to normal: you can click on it everywhere where text exists.

**Comment by asturur** [comment]
Yes strange. i would assume exitEditing has setCoords but may be not the case. very strange.

**Comment by asturur** [comment]
That link runs on latest beta, can you actually replicate on 1.7.19?

**Comment by finom** [comment]
Yes, 1.7.19 is the actual version I use.

**Comment by asturur** [comment]
is not super simple to replicate. i think i fixed it exagerating on recalucating the coordinates.
The cost of re rendering text when text change is anyway high, an added setCoords do not change anything.

**Comment by asturur** [comment]
i backported it in a lazy way in 1.x but i bakported it.
I really suggest you to swtich to 2.0

**Comment by pshurygin** [comment]
@asturur I am still having this issue with version 2.0.0 rc1. You can also easily reproduce it on the benchmark page 
http://fabricjs.com/test/misc/itext.html
Just enter some text in the first line so that itext becomes bigger, then click outside, then try to select it again by clicking on the far left side of itext. Also, if you click right in the middle of edited itext, blinking cursor appears in the wrong position(not where mouse cursor is pointing).

I tried to manually call setCoords() on 'before:selection:cleared', but that did not help as well. I guess there may be some problem with caching coordinates.
