### ISSUE TITLE
Resize filter works incorrectly after updating Chrome browser to latest version.

### ISSUE THREAD

**Issue by leesc81** [kangax/fabric.js#4659]
Resize filter works incorrectly after updating Chrome browser to latest version.

Problems occur when upgrading Chrome.
Problems occur on Desktop Chrome, Android Chrome browser, and Android WebView.
Other browsers have no problems at all.

When applying a Resize filter, the image will appear rotated upside down.

There is a problem when you shrink the image to a smaller size.

Updated chrome version
Desktop: 64.0.3282.119
Android: 64.0.3282.123

This is a serious problem, as it will cause problems when upgrading users.

## Version
2.0.0rc3 ~ rc4

## Steps to reproduce
Chrome  browser update(Desktop, Android both)

## Actual Behavior
When applying a Resize filter, the image will appear rotated upside down.
![screenshot_20180131-105434](https://user-images.githubusercontent.com/16448526/35601232-48de8b2e-0675-11e8-8c97-f5248ee7e626.jpg)

**Comment by asturur** [comment]
Chrome 64 is definitely broken, there are more defect.
Is hard to understand where they are and report them.
Since i think is well spread, i hope they will fix them soon.

**Comment by asturur** [comment]
Thanks very much for reporting

**Comment by jilster** [comment]
On the newest Chrome for Mac, 64.0.3282.119 (64bit), this problem does not occur (yet).

**Comment by asturur** [comment]
it occurs on mine.

**Comment by asturur** [comment]
are you on retina @jilster?

**Comment by jilster** [comment]
Yes i am on Retina, it's a new MacBook AIr. Just to be sure: i tested using this fiddle: https://jsfiddle.net/7g4k1rrf/11/ , It is a image that is scaled down using the Resize filter.

On iPhone X, Chrome 64.0.3282.112 , it does not occur either

**Comment by jilster** [comment]
Correction, it appears i don't have Retina

**Comment by leesc81** [comment]
Hi~ Im using Macbook pro touchbar 2016
Mac chrome version 64.0.3282.119
Android(Samsung Note 7) chrome version 64.0.3282.123

**Comment by jilster** [comment]
Are you guys on macOS High Sierra?

**Comment by leesc81** [comment]
Yes~ High Sierra 10.13.3

**Comment by jilster** [comment]
If you try https://jsfiddle.net/7g4k1rrf/11/, does it occur? Just to be sure i am testing it the right way

**Comment by asturur** [comment]
it happens on linux too on chrome 64.

**Comment by asturur** [comment]
![testp](https://user-images.githubusercontent.com/1194048/35671821-dad40b7c-073c-11e8-9f50-9034ed48260f.gif)

this is what i see

**Comment by asturur** [comment]
So my opinion based on pure gut feeling is that sometimes setTransform fails.
But from here to demonstrate it is a long road.

**Comment by jilster** [comment]
Yes, you are probably right. I really hope this gets fixed in Chrome. I managed to reproduce on Android (Samsung Galaxy S6) Chrome 64.0.3282.123

**Comment by leesc81** [comment]
@jilster Your fiddle will work fine.
Turning off enableGLFiltering can be a temporary solution...

**Comment by leesc81** [comment]
A new version of Chrome has been deployed.
64.0.3282.137
But the issue was not resolved.
When applying the resize filter, images are often rotated 180 degrees.

**Comment by asturur** [comment]
are not rotated, are flipped.
the setTransform(1,0,0,-1,0,0) is failing.

The problem do not involve webgl only, it happens in other occasions, harder to trigger, in my work app they happen.

**Comment by jilster** [comment]
I forgot, that fiddle was created before the resize filter worked with GPL. The results are interesting though:

Non retina MacBook Air, with webgl: Image is always upside down
Non retina MacBook Air, without webgl: Image is always correct
iPhone X, with webgl and without webgl: Image is always correct
Samsung Galaxy S6, with and without webgl: Image sometimes upside down and sometimes correct (just like @asturur showed)

**Comment by leesc81** [comment]
Another problem is that the large size image appears black.
In previous versions, there was no problem with the same image.
![20160710_183719](https://user-images.githubusercontent.com/16448526/35674246-6428a384-0787-11e8-8759-e2e2f19050da.jpg)

**Comment by jilster** [comment]
Could it be that Chrome made some changes in the way they render resizing to enable this feature:

https://developers.google.com/web/updates/2018/01/nic64#resizeobserver

I don't know if this has anything to do with resizing on a Canvas, but it can't be a coincidence that our resizing breaks when they push this right?

**Comment by Jandou6** [comment]
fabric version 1.x  broken  in Chrome 64 too

**Comment by asturur** [comment]
I would say chrome64 is broken in any version of fabric.
Fabric cannot fix chrome.
Those are the relate bugs i found on the chrome issue, they are aware of the problem:
https://bugs.chromium.org/p/chromium/issues/detail?id=808214
and linked ones.

**Comment by Aubron** [comment]
Just so others don't have to follow through their bug tracker: Chrome team has decided the hardware accelerated canvas bugs will be fixed in Chrome 65, and will not patch them in current chrome. They have said that  disabling hardware acceleration in chrome://flags is the recommended fix until 65 goes stable.

@asturur - any suggestions on code level workarounds? We're getting oddities all over the place in 64, and I'm not really willing to communicate to our clients a fix that involves chrome://flags.

**Comment by asturur** [comment]
I have the same problem and was thinking to bump up min cache size from 256 to 512+ hoping to trigger hardware acceleration.
I mean they are insane. a revert of the problematic commits and a quick patch was the most sane thing to do.

Disabling hardware acceleration means throw any website to shit speed. Excuse the word.

**Comment by Aubron** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=807636&q=component%3ABlink%3ECanvas&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by Aubron** [comment]
@asturur - Looks like we're getting a M64 fix 🎉

**Comment by asturur** [comment]
Chrome 64 looks like it got an update.
Can you verify that your app is fixed?

**Comment by jilster** [comment]
Chrome 64.0.3282.167 seems to be working a lot better, the issues i was having are fixed! 👏

**Comment by Aubron** [comment]
We’re seeing a return to sanity across the board. Thanks for helping troubleshoot! 🎉

**Comment by asturur** [comment]
i ll close this.

**Comment by leesc81** [comment]
Android Chrome browser(and WebView) has not been updated yet.

**Comment by asturur** [comment]
I understand, but is probably something i cannot take care of.
People normally do not search issues, just open a new one.
I'll try to leave it open hoping that they will use search.

**Comment by asturur** [comment]
this was a short burst of problem from chrome 64 only, we are near to chrome 66 i guess is safe to close.
